### ISSUE TITLE
Getting error in building procedure Ubuntu 15.04

### ISSUE THREAD

**Issue by GeorgeGkas** [cyberpython/glossa-interpreter#7]
I get the following errors in build procedure:
```
BUILD FAILED
/home/georgegks/glossa-interpreter-1.0.7/build.xml:29: Compile failed; see the compiler error output for details.

Total time: 6 seconds
Makefile:25: recipe for target 'all' failed
make: *** [all] Error 1
```

I won't post the `xml` file yet cause it won't help. What should I do? It would be best if you create a `ppa repository` and upload there the `jar` file

**Comment by cyberpython** [comment]
You are probably trying to build an older release of the interpreter. Versions 1.0.7 and earlier cannot be built on recent Ubuntu versions because the joptsimple library has been updated and it is not compatible with these older versions of glossa-interpreter. You need to build the latest release 1.0.8 (or the development version):

__Make sure the Ubuntu 'universe' repository is enabled in the 'Ubuntu Software Sources' application.__

__Install the dependencies with:__

    sudo apt-get install openjdk-7-jdk antlr3 libjoptsimple-java


__Install the latest glossa-interpreter:__

    cd ~
    wget https://dl.dropboxusercontent.com/u/599926/releases/glossa-interpreter-1.0.8.tar.gz
    tar -xvf glossa-interpreter-1.0.8.tar.gz
    cd glossa-interpreter-1.0.8
    make
    sudo make install

__Run lingua:__

    cd ~
    glossa-interpreter

**Comment by GeorgeGkas** [comment]
Thank you very much! :+1:
